# Generated by Django 4.2 on 2025-12-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("scan_time", models.DateTimeField(auto_now_add=True)),
                ("pattern", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-scan_time"],
            },
        ),
        migrations.CreateModel(
            name="StrategyTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Monitoring (Wait for Break)"),
                            ("PENDING_ENTRY", "Order Placed"),
                            ("OPEN", "Position Open"),
                            ("PENDING_EXIT", "Exit Order Placed"),
                            ("CLOSED", "Closed"),
                            ("EXPIRED", "Setup Expired"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("candle_timestamp", models.DateTimeField()),
                ("candle_open", models.DecimalField(decimal_places=2, max_digits=10)),
                ("candle_high", models.DecimalField(decimal_places=2, max_digits=10)),
                ("candle_low", models.DecimalField(decimal_places=2, max_digits=10)),
                ("candle_close", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prev_day_low", models.DecimalField(decimal_places=2, max_digits=10)),
                ("entry_level", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "entry_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exit_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "actual_entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_breakeven_moved", models.BooleanField(default=False)),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exit_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalTradingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_trades_per_day", models.IntegerField(default=10)),
                ("max_trades_per_symbol", models.IntegerField(default=2)),
                (
                    "risk_per_trade_amount",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                (
                    "volume_threshold",
                    models.BigIntegerField(
                        default=500000, help_text="Min volume * price to trade"
                    ),
                ),
                (
                    "risk_reward_ratio",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
                ),
                (
                    "breakeven_trigger_r",
                    models.DecimalField(decimal_places=2, default=1.25, max_digits=4),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FyersCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
